version: "3.8"

services:
  neo4j:
    image: neo4j:5.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - graphrag-network
    healthcheck:
      test:
        ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password123", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  weaviate:
    image: semitechnologies/weaviate:1.22.4
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - graphrag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 10s
      timeout: 10s
      retries: 5

  graphrag-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      neo4j:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./data:/app/data
      - ./sample_docs:/app/sample_docs
      - ./logs:/app/logs
    networks:
      - graphrag-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - graphrag-api
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - graphrag-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  weaviate_data:

networks:
  graphrag-network:
    driver: bridge
